projectoppi/compra/urls.py
from argparse import Namespace
from django.urls import path
from . import views

app_name = 'compra'
urlpatterns =[
    path('',views.CompraListView.as_view(), name='compra'),
    path('Crear/',views.CompraCreateView.as_view(), name='crearCompra'),
    path('update/<int:pk>',views.CompraUpdateView.as_view(),name='updCompra')
   
    
]

projectoppi/projectoppi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projecto.urls')),
    path('cliente/', include('cliente.urls')),
    path('proveedores/', include('proveedores.urls')),
    path('productos/', include('productos.urls')),
    path('tipoproductos/', include('tipoProducto.urls')),
    path('inventario/', include('inventario.urls')),
    path('user/', include('user.urls')),
    path('ventas/', include('ventas.urls')),
    path('compra/', include('compra.urls')),

]

projectoppi/proveedores/urls.py
from django.urls import path
from . import views

app_name = 'proveedores'
urlpatterns =[
    path('',views.ProvedoresListView.as_view(), name='proveedores'),
    path('crear',views.ProveedorCreateView.as_view(), name='crearProveedor'),
    path('cb/',views.selectProveedores, name='selectProveedores'),
    path('Editar/<int:pk>',views.ProveedoresUpdateView.as_view(), name='EditarProveedor'),
    path('Eliminar/<int:pk>',views.ProveedorDeleteView.as_view(), name='EliminarProveedor'),
   
    # path('registro/',views.cargar_registro, name='registro'),
]
    

projectoppi/user/urls.py
from django.urls import path
from user.views import *
from . import views

app_name = 'user'

urlpatterns = [
    # user
    path('', UserListView.as_view(), name='user_list'),
    path('CrearUser/',views.UserCreateView.as_view(), name='crearUser'),
    path('EditarUser/<int:pk>',views.UserUpdateView.as_view(), name='EditarUser'),
    path('EliminarUser/<int:pk>',views.UserDeleteView.as_view(), name='EliminarUser'),

]

projectoppi/compra/models.py
from datetime import datetime
from django.db import models
from proveedores.models import Proveedores
from productos.models import Productos
from django.forms import model_to_dict

# Create your models here.
class EstadoCompra(models.Model):
    estadoCompra_Id=models.IntegerField(verbose_name='Estado compra Id',primary_key=True)
    nombre=models.CharField(max_length=50,verbose_name='Nombre')
    descripcion=models.CharField(max_length=200,verbose_name='Descripcion')
    dateCreate=models.DateTimeField(auto_now=True,null=True,blank=True)
    dateUpdate=models.DateTimeField(auto_now_add=True,null=True,blank=True)

    def __str__(self) -> str:
        return self.nombre
    
    class Meta:
        db_table="tblEstadoCompra"

class Compra(models.Model):
    Compra_Id=models.AutoField(verbose_name='Compra Id',primary_key=True)
    proveedor=models.ForeignKey(Proveedores,on_delete=models.PROTECT,null=True,blank=True)
    estadoCompra=models.ForeignKey(EstadoCompra,on_delete=models.PROTECT,null=True,blank=True)
    fechaCompra=models.DateField(null=True,blank=True,verbose_name='Fecha compra',default=datetime.now)
    dateUpdate=models.DateField(null=True,blank=True, verbose_name='Fecha actualización',default=datetime.now)   
    total = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)



    def toJSON(self):
        item = model_to_dict(self)
        item['proveedor'] = self.proveedor.nombres
        item['estadoCompra'] = self.estadoCompra.nombre
        item['total'] = format(self.total, '.2f')
        item['fechaCompra'] = self.fechaCompra.strftime('%Y-%m-%d')
        return item
    
    class Meta:
        db_table="tblCompras"

class DetalleCompra(models.Model):
    detalleCompra=models.AutoField(verbose_name='Detalle compra Id',primary_key=True)
    compra=models.ForeignKey(Compra,on_delete=models.CASCADE,null=True,blank=True)
    producto=models.ForeignKey(Productos,on_delete=models.PROTECT,null=True,blank=True)
    cantidad=models.IntegerField(default=0,verbose_name='Cantidad')
    precioCompra=models.DecimalField(default=0.00,max_digits=9, decimal_places=2,verbose_name='Precio compra')    
    subtotal = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def toJSON(self):
        item = model_to_dict(self, exclude=['compra'])
        item['producto'] = self.producto.toJSON()
        item['precioCompra'] = format(self.precioCompra, '.2f')
        item['subtotal'] = format(self.subtotal, '.2f')
        return item
    
    class Meta:
        db_table="tblDetalleCompra"

projectoppi/compra/forms.py
from dataclasses import fields
from datetime import datetime
from select import select
from django.forms import *
from compra.models import *
from proveedores.models import *
from productos.models import Productos

class CompraForm(ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        

    class Meta:
        model=Compra
        fields='__all__'
        widgets={
        'proveedor':Select(
            attrs={
                'class':'form-control select2',

            }
        ),
        'estadoCompra':Select(
            attrs={
                'class':'form-control select2',

            }
        ),        
        'fechaCompra':DateInput(
            format='%Y-%m-%d',
            attrs={
                'value':datetime.now(),
                'class': 'form-control datetimepicker-input',
                'data-target': '#fechaCompra',
                'data-toggle': 'datetimepicker',
                'autocomplete': 'off',
                'id': 'fechaCompra',

            }
        ),
        'total': TextInput(attrs={
                'readonly': True,
                'class': 'form-control',
            })
        }
    
    proveedor = ModelChoiceField(queryset=Proveedores.objects.all(),label="Proveedor",widget=Select(
        attrs={'class':'form-control select2',
    }))
    estadoCompra = ModelChoiceField(queryset=EstadoCompra.objects.all(),label="Estado compra",widget=Select(
        attrs={'class':'form-control select2',
    }))

class DetalleCompraForm(ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

    class Meta:
        model=DetalleCompra
        fields='__all__'
        widgets={
        'producto':Select(
            attrs={
                'class':'form-control select2',

            }
        ),
        'Cantidad':NumberInput(
            attrs={
                'class':'form-control select2',

            }
        ),        
        'precioCompra':TextInput(
            attrs={
                'class':'form-control'

            }
        ),
        }
    
    producto = ModelChoiceField(queryset=Productos.objects.all(),label="Producto",widget=Select(
        attrs={'class':'form-control select2',
    }))

projectoppi/compra/views.py
from datetime import date, datetime
import json

from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, View
from compra.forms import CompraForm
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.db import transaction
from compra.models import Compra, DetalleCompra
from productos.models import Productos
from django.utils.dateparse import parse_date

class CompraListView(ListView):
    model=Compra
    template_name = 'compra/list.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)


    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Compra.objects.all():
                    data.append(i.toJSON())
            elif action == 'search_details_prod':
                data = []
                for i in DetalleCompra.objects.filter(compra_id=request.POST['Compra_Id']):
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de compras'
        context['titlepag'] = 'Compras'
        return context

class CompraCreateView(CreateView):
    model: Compra
    form_class=CompraForm
    template_name= 'compra/create.html'
    success_url=reverse_lazy('compra:compra')
    
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        print('prid')
        data = {}
        try:
            action = request.POST['action']
            if action == 'search_products':
                data = []
                prods = Productos.objects.filter(nombre__icontains=request.POST['term'])[0:10]
                print(prods)
                for i in prods:
                    print('prid')
                    item = i.toJSON()
                    item['value'] = i.nombre
                    data.append(item)
                
            elif action == 'add':
                with transaction.atomic():
                    compras = json.loads(request.POST['compras'])
                    print(compras)
                    
                    compra = Compra()
                    compra.fechaCompra = compras['fechaCompra']
                    compra.dateUpdate=datetime.now()
                    compra.proveedor_id =compras['proveedor']
                    compra.estadoCompra_id = float(compras['estadoCompra'])
                    compra.total = float(compras['total'])
                    compra.save()
                    for i in compras['productos']:
                        prod=Productos()
                        prods = Productos.objects.filter(id=i['id'])
                        for k in prods:
                            prod.id=i['id']
                            prod.nombre=k.nombre
                            prod.descripcion=k.descripcion
                            prod.tipoProducto_id=k.tipoProducto_id
                            prod.cantidad=int(k.cantidad)+int(i['cantidad'])
                            prod.precio_venta=float(k.precio_venta)
                        prod.save()
                        
                        det = DetalleCompra()
                        det.compra_id = compra.Compra_Id
                        det.producto_id = i['id']
                        det.cantidad = int(i['cantidad'])
                        det.precioCompra = float(i['precio_compra'])
                        det.subtotal = float(i['subtotal'])
                        det.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)


    def get_context_data(self, **kwargs):
            context=super().get_context_data(**kwargs)
            context['url'] = reverse_lazy('compra:crearCompra')
            context['action'] = 'add'
            return context

class CompraUpdateView(UpdateView):
    model: Compra
    form_class=CompraForm
    template_name= 'compra/create.html'
    success_url=reverse_lazy('compra:compra')
    
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        print('prid')
        data = {}
        try:
            action = request.POST['action']
            if action == 'search_products':
                data = []
                prods = Productos.objects.filter(nombre__icontains=request.POST['term'])[0:10]
                for i in prods:
                    print('prid')
                    item = i.toJSON()
                    item['value'] = i.nombre
                    data.append(item)
            elif action == 'edit':
                with transaction.atomic():
                    compras = json.loads(request.POST['compras'])
                    print(compras)
                    
                    compra = Compra()
                    compra.fechaCompra = compras['fechaCompra']
                    compra.dateUpdate=datetime.now()
                    compra.proveedor_id =compras['proveedor']
                    compra.estadoCompra_id = float(compras['estadoCompra'])
                    compra.total = float(compras['total'])
                    compra.save()
                    for i in compras['productos']:
                        prod=Productos()
                        prods = Productos.objects.filter(id=i['id'])
                        for k in prods:
                            prod.id=i['id']
                            prod.nombre=k.nombre
                            prod.descripcion=k.descripcion
                            prod.tipoProducto_id=k.tipoProducto_id
                            prod.cantidad=int(k.cantidad)+int(i['cantidad'])
                            prod.precio_venta=float(k.precio_venta)
                        prod.save()
                        
                        det = DetalleCompra()
                        det.compra_id = compra.Compra_Id
                        det.producto_id = i['id']
                        det.cantidad = int(i['cantidad'])
                        det.precioCompra = float(i['precio_compra'])
                        det.subtotal = float(i['subtotal'])
                        det.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)


    def get_context_data(self, **kwargs):
        print('updated')
        context=super().get_context_data(**kwargs)
        context['url'] = reverse_lazy('compra:crearCompra')
        context['action'] = 'edit'
        return context

projectoppi/compra/templates/compra/create.html
<div class="modal-dialog modal-dialog-scrollable modal-xl" role="document">
    <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Compras</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            {% block content %}
                <form method="post">
                    <div class="card card-primary">

                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-8">
                                    <div class="card card-secondary">
                                        <div class="card-header">
                                            <h3 class="card-title"><i class="bi  bi-boxes"></i> Detalle de productos</h3>
                                        </div>
                                        <div class="card-body">
                                            <div class="form-group">
                                                <label>Buscador de productos:</label>
                                                <div class="input-group">
                                                    <input type="text" class="form-control" name="search"
                                                        placeholder="Ingrese una descripción de producto" autocomplete="off">
                                                    <span class="input-group-append">
                                                    <button type="button" class="btn btn-danger btn-flat bi bi-x"><i
                                                            class="fas fa-times"></i></button>
                                                </span>
                                                </div>
                                            </div>
                                            <hr>
                                            <button type="button" class="btn btn-danger btn-xs btnRemoveAll">
                                                <i class="bi bi-trash-fill"></i> Eliminar todos mis items
                                            </button>
                                            <hr>
                                            <table class="table table-bordered" id="tblProductos">
                                                <thead>
                                                <tr>
                                                    <th>Eliminar</th>
                                                    <th>Producto</th>
                                                    <th>Categoría</th>
                                                    <th>Precio compra</th>
                                                    <th>Cantidad</th>
                                                    <th>Subtotal</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="card card-secondary">
                                        <div class="card-header">
                                            <h3 class="card-title"><i class="bi bi-cart-fill"></i> Datos de la compra</h3>
                                        </div>
                                        <div class="card-body">
                                            <input type="hidden" name="action" value="{{ action }}">
                                            <div class="form-group">
                                                <label>Fecha de compra:</label>
                                                {{ form.fechaCompra }}
                                                
                                            </div>
                                            <div class="form-group">
                                                <label>Proveedor:</label>
                                                {{ form.proveedor }}
                                                
                                            </div>
                                            <div class="form-group">
                                                <label>Estado compra:</label>
                                                {{ form.estadoCompra }}
                                                
                                            </div>
                                            
                                                                                        
                                            <div class="form-group">
                                                <label>Total compra:</label>
                                                {{ form.total }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary btn-flat">
                                <i class="fas fa-save"></i> Guardar registro
                            </button>
                           
                        </div>
                    </div>
                </form>
            {% endblock %}
          
        </div>
    </div>
  </div>

  {% load static %}
  {% block head_list %}
      <script src="{% static '/js/form.js' %}"></script>
  {% endblock %}

projectoppi/compra/templates/compra/list.html
{% extends 'list.html' %}
{% load static %}
{% block head_list %}
    <script src="{% static '/js/list.js' %}"></script>
{% endblock %}
 
{% block botones %}
  <div style="position: absolute; z-index: 1; right: 10px; top: 95px;" >
    <button onclick="openPopup('{% url 'compra:crearCompra' %}')" class="btn btn-primary">Crear</button>  
    <button onclick="openModelEdit('{% url 'compra:updCompra' 0  %}')" class="btn btn-primary">Modificar</button>
    <button onclick="deleteRegister('{% url 'proveedores:EliminarProveedor' 0  %}','/proveedores/')" class="btn btn-primary">Eliminar</button>
    <button onclick="openBuscar()" class="btn btn-primary">Buscar</button>
  </div>
{% endblock %}

{% block columns %}
  <tr>
    <th>Codigo</th>
    <th>Proveedor</th>
    <th>Fecha de registro</th>
    <th>Total</th>
    <th>Estado</th>
    <th>Opciones</th>

  </tr>
{% endblock %}
                
{% block rows %}
  

{% endblock %}
{% block extrajsmodel %}
<div class="modal fade" id="myModelDet" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
aria-hidden="true">
<div class="modal-dialog modal-lg" role="document">
   <div class="modal-content">
       <div class="modal-header">
           <h5 class="modal-title" id="exampleModalLabel"><b><i class="fas fa-shopping-cart"></i> Consulta de
               detalle de productos</b></h5>
               <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
               
       </div>
       <div class="modal-body">
           <table class="table table-bordered" id="tblDet">
               <thead>
               <tr>
                   <th>Producto</th>
                   <th>Categoría</th>
                   <th>Precio Compra</th>
                   <th>Cantidad</th>
                   <th>Subtotal</th>
               </tr>
               </thead>
               <tbody>
               </tbody>
           </table>
       </div>
   </div>
</div>
</div>

{% endblock %}